import { useState, useEffect } from 'react'
import { KJV_BOOKS } from '../data/bibleData'
import SEO from '../components/SEO'
import PrayerTab from '../components/PrayerTab'

// Popular verses — always available instantly, no fetch needed
const POPULAR = [
  { ref: 'John 3:16', book: 'JHN', ch: 3, v: 16 },
  { ref: 'Philippians 4:13', book: 'PHP', ch: 4, v: 13 },
  { ref: 'Jeremiah 29:11', book: 'JER', ch: 29, v: 11 },
  { ref: 'Psalm 23:1', book: 'PSA', ch: 23, v: 1 },
  { ref: 'Romans 8:28', book: 'ROM', ch: 8, v: 28 },
  { ref: 'Proverbs 3:5', book: 'PRO', ch: 3, v: 5 },
  { ref: 'Isaiah 40:31', book: 'ISA', ch: 40, v: 31 },
  { ref: 'Matthew 6:33', book: 'MAT', ch: 6, v: 33 },
  { ref: 'Psalm 119:105', book: 'PSA', ch: 119, v: 105 },
  { ref: '2 Timothy 3:16', book: '2TI', ch: 3, v: 16 },
  { ref: 'Romans 10:9', book: 'ROM', ch: 10, v: 9 },
  { ref: 'Hebrews 11:1', book: 'HEB', ch: 11, v: 1 },
]

// KJV text is bundled with the app (public/data/kjv-bible.json — generated by
// scripts/transform-bible.mjs at build time) instead of fetched from a
// third-party CDN at runtime. Fetched once as a local same-origin request
// (fast, cacheable, no external dependency), then kept in memory for the
// session. The service worker caches it permanently after that first fetch,
// so repeat visits — including fully offline ones — never re-fetch it.
const BIBLE_DATA_URL = '/data/kjv-bible.json'

// In-memory store for the session — the whole parsed Bible once loaded
let KJV_MEMORY = null

function useStorage(key, def) {
  const [val, setVal] = useState(() => {
    try { const s = localStorage.getItem(key); return s ? JSON.parse(s) : def } catch { return def }
  })
  const save = v => { setVal(v); try { localStorage.setItem(key, JSON.stringify(v)) } catch {} }
  return [val, save]
}

// Highlight matched words in a verse text — returns array of {text, highlight} segments
function highlightWords(text, query) {
  if (!query.trim()) return [{ text, highlight: false }]
  const parts = []
  const lower = text.toLowerCase()
  const q = query.toLowerCase().trim()
  let i = 0
  while (i < text.length) {
    const idx = lower.indexOf(q, i)
    if (idx === -1) { parts.push({ text: text.slice(i), highlight: false }); break }
    if (idx > i) parts.push({ text: text.slice(i, idx), highlight: false })
    parts.push({ text: text.slice(idx, idx + q.length), highlight: true })
    i = idx + q.length
  }
  return parts
}

// Load the bundled Bible JSON once (from cache on repeat visits)
async function loadFullBible(onProgress) {
  if (KJV_MEMORY) return KJV_MEMORY
  try {
    onProgress('Loading Bible...')
    const res = await fetch(BIBLE_DATA_URL)
    if (!res.ok) throw new Error('Could not load bundled Bible data')
    KJV_MEMORY = await res.json()
    onProgress('')
    return KJV_MEMORY
  } catch (e) {
    onProgress('')
    throw e
  }
}

export default function Bible() {
  const OT = KJV_BOOKS.filter(b => b.testament === 'OT')
  const NT = KJV_BOOKS.filter(b => b.testament === 'NT')

  const [selBook, setSelBook] = useStorage('bible_book', KJV_BOOKS[39])
  const [selChapter, setSelChapter] = useStorage('bible_chapter', 1)
  const [verses, setVerses] = useState([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [tab, setTab] = useState('read')
  const [fontSize, setFontSize] = useStorage('bible_fontsize', 17)
  const [bookTab, setBookTab] = useState('NT')
  const [bookOpen, setBookOpen] = useState(false)
  const [isOnline, setIsOnline] = useState(navigator.onLine)
  const [cacheStatus, setCacheStatus] = useState('idle')
  const [downloadProgress, setDownloadProgress] = useState('')
  const [search, setSearch] = useState('')
  const [searchResults, setSearchResults] = useState([])
  const [searchTotal, setSearchTotal] = useState(0)
  const [highlightVerse, setHighlightVerse] = useState(null)
  const [popularVerses, setPopularVerses] = useState({})

  useEffect(() => {
    const on = () => setIsOnline(true), off = () => setIsOnline(false)
    window.addEventListener('online', on); window.addEventListener('offline', off)
    return () => { window.removeEventListener('online', on); window.removeEventListener('offline', off) }
  }, [])

  // Load the bundled Bible on mount — works offline too, since for the native
  // app this file ships inside the app bundle itself, and for the web PWA
  // it's cached by the service worker after the first successful fetch.
  useEffect(() => {
    if (cacheStatus === 'idle') {
      setCacheStatus('loading')
      loadFullBible(msg => setDownloadProgress(msg))
        .then(() => setCacheStatus('done'))
        .catch(() => setCacheStatus('idle'))
    }
  }, [])

  // Load popular verse texts once the bundled Bible is available
  useEffect(() => {
    if (cacheStatus !== 'done' || !KJV_MEMORY) return
    const loaded = {}
    for (const pv of POPULAR) {
      const found = KJV_MEMORY?.[pv.book]?.[pv.ch]?.find(v => v.verse === pv.v)
      if (found) loaded[pv.ref] = found.text
    }
    setPopularVerses(loaded)
  }, [cacheStatus])

  const loadChapter = async (book, chapter) => {
    setLoading(true); setError(null); setVerses([])
    try {
      const bible = await loadFullBible(msg => setDownloadProgress(msg))
      const chVerses = bible?.[book.id]?.[chapter]
      if (chVerses) {
        setVerses(chVerses)
        setLoading(false)
        return
      }
      if (!navigator.onLine) {
        setError('This chapter isn\'t available offline yet.')
        setLoading(false)
        return
      }
      // Bundled data missing this specific chapter somehow — rare fallback
      const slug = book.name.toLowerCase().replace(/ /g, '+')
      fetch(`https://bible-api.com/${slug}+${chapter}?translation=kjv`)
        .then(r => r.json())
        .then(data => {
          const v = data.verses || []
          setVerses(v)
          try { localStorage.setItem(key, JSON.stringify(v)) } catch {}
          setLoading(false)
        })
        .catch(() => { setError('Could not load chapter.'); setLoading(false) })
    } catch (e) {
      setError('Error: ' + e.message); setLoading(false)
    }
  }

  useEffect(() => { loadChapter(selBook, selChapter) }, [selBook.id, selChapter])

  const handleBook = book => { setSelBook(book); setSelChapter(1); setBookOpen(false); setHighlightVerse(null) }

  const goToVerse = (bookId, ch, v) => {
    const book = KJV_BOOKS.find(b => b.id === bookId)
    if (book) { setSelBook(book); setSelChapter(ch); setHighlightVerse(v); setTab('read') }
  }

  const runSearch = (q) => {
    if (!q.trim()) { setSearchResults([]); setSearchTotal(0); return }
    if (cacheStatus !== 'done') {
      setSearchResults([{ reference: '', text: cacheStatus === 'loading'
        ? 'Bible is still loading. Search will be ready in a moment.'
        : 'Could not load the Bible data — try again.' }])
      setSearchTotal(0)
      return
    }
    const lower = q.toLowerCase().trim()
    const results = []
    let total = 0
    for (const book of KJV_BOOKS) {
      const bookData = KJV_MEMORY?.[book.id]
      if (!bookData) continue
      for (let ci = 1; ci <= book.chapters; ci++) {
        const chVerses = bookData[ci]
        if (!chVerses) continue
        for (const v of chVerses) {
          if (v.text && v.text.toLowerCase().includes(lower)) {
            total++
            if (results.length < 100) {
              results.push({ book, chapter: ci, verse: v.verse, text: v.text, reference: `${book.name} ${ci}:${v.verse}` })
            }
          }
        }
      }
    }
    setSearchResults(results)
    setSearchTotal(total)
  }

  const handleSearch = e => {
    e.preventDefault()
    runSearch(search)
  }

  const chNums = Array.from({ length: selBook.chapters }, (_, i) => i + 1)

  const statusBadge = cacheStatus === 'done'
    ? { label: '✅ Full Bible Cached — 100% Offline', color: 'rgba(74,184,102,0.25)', text: '#a8e6b8', border: 'rgba(74,184,102,0.4)' }
    : cacheStatus === 'loading'
    ? { label: '⏳ Loading Bible...', color: 'rgba(255,200,0,0.2)', text: '#ffe066', border: 'rgba(255,200,0,0.4)' }
    : { label: '☁️ Connect to cache Bible offline', color: 'rgba(255,150,50,0.2)', text: '#ffcc88', border: 'rgba(255,150,50,0.4)' }

  return (
    <>
      <SEO
        title="Bible"
        description="Read the full King James Version Bible online and offline. CCG World — Christian Church Of God Mission."
        path="/bible"
      />
      <div style={{ background: 'linear-gradient(160deg,rgba(10,38,18,0.93) 0%,rgba(22,100,52,0.87) 55%,rgba(22,163,74,0.45) 100%),url("https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=1600&q=80") center/cover no-repeat', padding: 'clamp(80px,12vw,120px) 5% 0' }}>
        <div className="container">
          <div className="bible-header-row" style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16, paddingBottom: 24 }}>
            <div>
              <span className="section-label" style={{ color: 'var(--green-light)' }}>King James Version</span>
              <h1 style={{ fontFamily: 'var(--font-display)', color: 'white', fontSize: 'clamp(2rem,5vw,3rem)', margin: '4px 0 10px' }}>📖 Holy Bible</h1>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                <span style={{ padding: '4px 14px', borderRadius: 20, fontSize: '0.72rem', fontWeight: 700, background: statusBadge.color, color: statusBadge.text, border: `1px solid ${statusBadge.border}` }}>
                  {statusBadge.label}
                </span>
                {downloadProgress && (
                  <span style={{ padding: '4px 14px', borderRadius: 20, fontSize: '0.72rem', color: 'rgba(255,255,255,0.7)', background: 'rgba(0,0,0,0.2)' }}>{downloadProgress}</span>
                )}
                <span style={{ padding: '4px 14px', borderRadius: 20, fontSize: '0.72rem', fontWeight: 700, background: isOnline ? 'rgba(74,184,102,0.15)' : 'rgba(255,100,100,0.2)', color: isOnline ? '#a8e6b8' : '#ffaaaa', border: '1px solid rgba(255,255,255,0.15)' }}>
                  {isOnline ? '🟢 Online' : '🔴 Offline'}
                </span>
              </div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, background: 'rgba(255,255,255,0.12)', borderRadius: 30, padding: '6px 16px' }}>
              <button onClick={() => setFontSize(f => Math.max(13, f - 1))} style={{ background: 'none', border: 'none', color: 'white', fontSize: '1rem', cursor: 'pointer' }}>A−</button>
              <span style={{ color: 'rgba(255,255,255,0.6)', fontSize: '0.78rem', minWidth: 30, textAlign: 'center' }}>{fontSize}px</span>
              <button onClick={() => setFontSize(f => Math.min(24, f + 1))} style={{ background: 'none', border: 'none', color: 'white', fontSize: '1.1rem', cursor: 'pointer' }}>A+</button>
            </div>
          </div>
          <div className="bible-tabs" style={{ display: 'flex', gap: 4 }}>
            {[['read','📖','Read'],['search','🔍','Search'],['popular','⭐','Popular'],['prayer','🙏','Mood']].map(([t,icon,label]) => (
              <button key={t} onClick={() => setTab(t)} style={{
                padding: '10px 22px', borderRadius: '10px 10px 0 0', border: 'none', cursor: 'pointer',
                background: tab === t ? 'var(--cream)' : 'rgba(255,255,255,0.15)',
                color: tab === t ? 'var(--green-deep)' : 'rgba(255,255,255,0.9)',
                fontWeight: 700, fontSize: '0.85rem', fontFamily: 'var(--font-body)',
              }}>{icon} <span className="bible-tab-label">{label}</span></button>
            ))}
          </div>
        </div>
      </div>

      <div style={{ background: 'var(--cream)', minHeight: '70vh', padding: '0 5% 60px' }}>
        <div className="container">

          {tab === 'read' && (
            <div className="bible-reader-grid" style={{ display: 'grid', gridTemplateColumns: '260px 1fr', gap: 24, paddingTop: 28 }}>
              <div>
                <div style={{ background: 'var(--white, white)', borderRadius: 14, boxShadow: 'var(--shadow-sm)', overflow: 'hidden', marginBottom: 14 }}>
                  <button onClick={() => setBookOpen(o => !o)} style={{
                    width: '100%', padding: '13px 18px', background: 'var(--brand-base)', color: 'white',
                    border: 'none', cursor: 'pointer', fontFamily: 'var(--font-display)',
                    fontSize: '1rem', fontWeight: 700, textAlign: 'left', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                  }}>
                    <span>{selBook.name}</span><span style={{ fontSize: '0.7rem' }}>{bookOpen ? '▲' : '▼'}</span>
                  </button>
                  {bookOpen && (
                    <div style={{ maxHeight: 360, overflowY: 'auto' }}>
                      <div style={{ display: 'flex', borderBottom: '1px solid var(--brand-pale)', position: 'sticky', top: 0, background: 'var(--white, white)', zIndex: 1 }}>
                        {['OT','NT'].map(t => (
                          <button key={t} onClick={() => setBookTab(t)} style={{
                            flex: 1, padding: '9px', border: 'none', cursor: 'pointer',
                            background: bookTab === t ? 'var(--brand-pale)' : 'var(--white, white)',
                            color: bookTab === t ? 'var(--green-deep)' : 'var(--text-mid)',
                            fontWeight: 700, fontSize: '0.82rem', fontFamily: 'var(--font-body)',
                          }}>{t === 'OT' ? 'Old Testament' : 'New Testament'}</button>
                        ))}
                      </div>
                      {(bookTab === 'OT' ? OT : NT).map(book => {
                        const isCached = cacheStatus === 'done'
                        return (
                          <button key={book.id} onClick={() => handleBook(book)} style={{
                            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                            width: '100%', padding: '9px 16px', border: 'none', cursor: 'pointer',
                            background: selBook.id === book.id ? 'var(--green-pale)' : 'var(--white, white)',
                            color: selBook.id === book.id ? 'var(--green-deep)' : 'var(--text-dark)',
                            fontWeight: selBook.id === book.id ? 700 : 400,
                            fontSize: '0.88rem', textAlign: 'left', fontFamily: 'var(--font-body)',
                            borderBottom: '1px solid #f5f5f5',
                          }}>
                            <span>{book.name}</span>
                            {isCached && <span style={{ fontSize: '0.62rem', color: 'var(--green-mid)', fontWeight: 700 }}>✓</span>}
                          </button>
                        )
                      })}
                    </div>
                  )}
                </div>
                <div style={{ background: 'var(--white, white)', borderRadius: 14, boxShadow: 'var(--shadow-sm)', padding: 14, marginBottom: 12 }}>
                  <div style={{ fontSize: '0.72rem', fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-light)', marginBottom: 10 }}>Chapter</div>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5,1fr)', gap: 5 }}>
                    {chNums.map(n => (
                      <button key={n} onClick={() => setSelChapter(n)} style={{
                        padding: '7px 4px', borderRadius: 7, border: '1.5px solid',
                        borderColor: selChapter === n ? 'var(--brand-base)' : '#eee',
                        background: selChapter === n ? 'var(--brand-base)' : 'var(--white, white)',
                        color: selChapter === n ? 'white' : 'var(--text-dark)',
                        fontSize: '0.8rem', fontWeight: 700, cursor: 'pointer', fontFamily: 'var(--font-body)',
                      }}>{n}</button>
                    ))}
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button onClick={() => { if (selChapter > 1) setSelChapter(c => c - 1) }} className="btn btn-outline-green" style={{ flex: 1, padding: '9px', fontSize: '0.82rem', justifyContent: 'center' }}>← Prev</button>
                  <button onClick={() => { if (selChapter < selBook.chapters) setSelChapter(c => c + 1) }} className="btn btn-green" style={{ flex: 1, padding: '9px', fontSize: '0.82rem', justifyContent: 'center' }}>Next →</button>
                </div>
              </div>

              <div style={{ background: 'var(--white, white)', borderRadius: 14, boxShadow: 'var(--shadow-sm)', padding: '32px 36px', minHeight: 500 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24, paddingBottom: 16, borderBottom: '2px solid var(--green-pale)' }}>
                  <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--green-deep)', fontSize: '1.5rem', margin: 0 }}>{selBook.name} {selChapter}</h2>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-light)' }}>{verses.length} verses</span>
                </div>
                {loading && <div style={{ textAlign: 'center', padding: 60, color: 'var(--text-light)' }}><div style={{ fontSize: '2rem', marginBottom: 10 }}>📖</div>Loading...</div>}
                {error && <div style={{ background: '#fff9f0', border: '1px solid #ffd', borderRadius: 10, padding: '18px 20px', color: '#885500', lineHeight: 1.7 }}>📵 {error}</div>}
                {!loading && !error && verses.map(v => (
                  <p key={v.verse} style={{
                    fontSize, lineHeight: 1.95, marginBottom: 10, color: 'var(--text-dark)',
                    background: highlightVerse === v.verse ? 'var(--green-pale)' : 'transparent',
                    borderRadius: 6, padding: highlightVerse === v.verse ? '4px 8px' : '0',
                    transition: 'background 0.4s',
                  }}>
                    <sup style={{ color: 'var(--green-mid)', fontWeight: 900, fontSize: '0.72em', marginRight: 5 }}>{v.verse}</sup>
                    {v.text}
                  </p>
                ))}
              </div>
            </div>
          )}

          {tab === 'search' && (
            <div style={{ paddingTop: 32, maxWidth: 800 }}>
              {/* Search bar */}
              <div style={{ display: 'flex', gap: 12, marginBottom: 10 }}>
                <input
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                  onKeyDown={e => e.key === 'Enter' && runSearch(search)}
                  placeholder='Search the entire KJV Bible — e.g. "grace", "faith", "love"'
                  style={{ flex: 1, padding: '13px 20px', borderRadius: 40, border: '1.5px solid #ddd', fontSize: '1rem', fontFamily: 'var(--font-body)', outline: 'none', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' }}
                  autoFocus
                />
                <button onClick={handleSearch} className="btn btn-green" style={{ whiteSpace: 'nowrap' }}>🔍 Search</button>
              </div>

              {/* Status line */}
              {cacheStatus !== 'done' && (
                <div style={{ background: '#fff9e6', border: '1px solid #ffe066', borderRadius: 10, padding: '10px 16px', marginBottom: 16, fontSize: '0.85rem', color: '#665500' }}>
                  ⏳ {cacheStatus === 'loading'
                    ? 'Bible is still loading — search will be ready shortly.'
                    : 'Could not load the Bible data — try reopening this page.'}
                </div>
              )}
              {searchTotal > 0 && (
                <div style={{ marginBottom: 16, fontSize: '0.82rem', color: 'var(--text-light)' }}>
                  {searchTotal > 100
                    ? `Showing first 100 of ${searchTotal.toLocaleString()} results for "${search}"`
                    : `${searchTotal.toLocaleString()} result${searchTotal === 1 ? '' : 's'} for "${search}"`}
                </div>
              )}
              {searchResults.length === 0 && search.trim() && searchTotal === 0 && cacheStatus === 'done' && (
                <div style={{ textAlign: 'center', padding: '48px 20px', color: 'var(--text-light)' }}>
                  <div style={{ fontSize: '2rem', marginBottom: 10 }}>🔍</div>
                  No verses found for <strong>"{search}"</strong>
                </div>
              )}

              {/* Results */}
              {searchResults.map((r, i) => (
                <div key={i} onClick={() => r.reference && goToVerse(r.book?.id, r.chapter, r.verse)} style={{
                  background: 'var(--white, white)', borderRadius: 12, padding: '16px 20px', marginBottom: 10,
                  boxShadow: 'var(--shadow-sm)', borderLeft: `4px solid ${r.reference ? 'var(--green-mid)' : '#ddd'}`,
                  cursor: r.reference ? 'pointer' : 'default', transition: 'transform 0.15s',
                }}
                onMouseEnter={e => r.reference && (e.currentTarget.style.transform = 'translateX(4px)')}
                onMouseLeave={e => e.currentTarget.style.transform = 'translateX(0)'}>
                  {r.reference && (
                    <div style={{ fontWeight: 700, color: 'var(--green-deep)', marginBottom: 6, fontSize: '0.85rem' }}>
                      {r.reference}
                    </div>
                  )}
                  <p style={{ fontSize: fontSize - 1, lineHeight: 1.8, color: r.reference ? 'var(--text-dark)' : 'var(--text-light)', margin: 0 }}>
                    {r.reference
                      ? highlightWords(r.text, search).map((seg, si) => (
                          <span key={si} style={seg.highlight ? {
                            background: '#fff176', color: '#333', borderRadius: 3,
                            padding: '0 2px', fontWeight: 700,
                          } : {}}>
                            {seg.text}
                          </span>
                        ))
                      : r.text}
                  </p>
                </div>
              ))}
            </div>
          )}

          {tab === 'popular' && (
            <div style={{ paddingTop: 32 }}>
              <p style={{ color: 'var(--text-mid)', marginBottom: 28 }}>
                Click any verse to open it in the reader. {cacheStatus === 'done' ? '✅ All cached offline.' : '⏳ Caching in background when online...'}
              </p>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: 18 }}>
                {POPULAR.map(v => (
                  <div key={v.ref} onClick={() => goToVerse(v.book, v.ch, v.v)} style={{
                    background: 'var(--white, white)', borderRadius: 14, padding: '22px',
                    boxShadow: 'var(--shadow-sm)', borderTop: '4px solid var(--green-mid)',
                    cursor: 'pointer', transition: 'transform 0.2s, box-shadow 0.2s',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-4px)'; e.currentTarget.style.boxShadow = 'var(--shadow-md)' }}
                  onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = 'var(--shadow-sm)' }}>
                    <div style={{ fontFamily: 'var(--font-display)', color: 'var(--gold)', fontSize: '1rem', fontWeight: 700, marginBottom: 10 }}>{v.ref}</div>
                    <p style={{ fontSize: fontSize - 1, lineHeight: 1.85, color: 'var(--text-dark)', fontStyle: 'italic', margin: '0 0 12px' }}>
                      {popularVerses[v.ref]
                        ? `"${popularVerses[v.ref]}"`
                        : <span style={{ color: 'var(--text-light)', fontStyle: 'normal' }}>{isOnline ? 'Loading...' : 'Tap to read'}</span>}
                    </p>
                    <div style={{ fontSize: '0.72rem', color: 'var(--green-mid)', fontWeight: 700 }}>→ Read in context</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {tab === 'prayer' && <PrayerTab onOpenVerse={goToVerse} />}

        </div>
      </div>
      <style>{`
        @media(max-width:768px){
          .bible-reader-grid{grid-template-columns:1fr!important;}
          .bible-header-row{flex-direction:column!important;align-items:flex-start!important;gap:12px!important;}
          .bible-tabs button{padding:8px 14px!important;font-size:0.8rem!important;}
        }
      `}</style>
    </>
  )
}
